import os
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv

load_dotenv()

def _get_spotify_client():
    try:
        sp_oauth = SpotifyOAuth(
            client_id=os.getenv('SPOTIPY_CLIENT_ID'),
            client_secret=os.getenv('SPOTIPY_CLIENT_SECRET'),
            redirect_uri=os.getenv('SPOTIPY_REDIRECT_URI'),
            scope='playlist-modify-private'
        )
        sp = spotipy.Spotify(auth_manager=sp_oauth)
        user_id = sp.current_user()['id']
        print(f"Authenticated as: {sp.current_user()['display_name']}")
        return sp, user_id
    except Exception as e:
        print(f"Error during Spotify authentication: {e}")
        print("Please check your SPOTIPY environment variables and redirect URI setup.")
        return None, None

def create_playlist_from_artists(artists, mood, playlist_name):
    sp, user_id = _get_spotify_client()
    if not sp:
        return None, None
    
    track_uris = []
    found_songs = []
    print("--- Searching for artists' top tracks ---")
    
    for artist_name in artists:
        try:
            results = sp.search(q=f"artist:{artist_name}", type='artist', limit=1)
            if not results['artists']['items']:
                print(f"Could not find artist: {artist_name}")
                continue
            
            artist_uri = results['artists']['items'][0]['uri']
            
            top_tracks = sp.artist_top_tracks(artist_uri)['tracks']
            
            for track in top_tracks[:2]:
                track_uris.append(track['uri'])
                found_songs.append({'artist': track['artists'][0]['name'], 'song': track['name']})
                print(f"Found track for {artist_name}: '{track['name']}'")

        except spotipy.exceptions.SpotifyException as e:
            print(f"Error processing artist {artist_name}: {e}")
    
    if not track_uris:
        print("Could not find any tracks on Spotify for the recommended artists.")
        return None, None

    playlist_description = f"Generated by AI based on a {mood} mood."
    
    playlist = sp.user_playlist_create(
        user=user_id,
        name=playlist_name,
        public=False,
        description=playlist_description
    )

    sp.playlist_add_items(playlist_id=playlist['id'], items=track_uris)
    playlist_url = playlist['external_urls']['spotify']
    print(f"Successfully created playlist '{playlist_name}'!")
    
    return playlist_url, found_songs


def create_playlist_for_one_artist(artist_name, playlist_name):
    sp, user_id = _get_spotify_client()
    if not sp:
        return None, None

    try:
        results = sp.search(q=f"artist:{artist_name}", type='artist', limit=1)
        if not results['artists']['items']:
            print(f"Could not find artist: {artist_name}")
            return None, None
        
        artist = results['artists']['items'][0]
        artist_uri = artist['uri']
        found_artist_name = artist['name']
        print(f"Found artist: {found_artist_name} (URI: {artist_uri})")

        top_tracks = sp.artist_top_tracks(artist_uri)['tracks']
        
        if not top_tracks:
            print(f"Found artist {found_artist_name} but no top tracks.")
            return None, None

        track_uris = []
        found_songs = []
        for track in top_tracks[:15]:
            track_uris.append(track['uri'])
            found_songs.append({'artist': track['artists'][0]['name'], 'song': track['name']})
            
    except spotipy.exceptions.SpotifyException as e:
        print(f"Error processing artist {artist_name}: {e}")
        return None, None
    
    playlist_description = f"The best songs by {found_artist_name}, generated by AI."
    
    playlist = sp.user_playlist_create(
        user=user_id,
        name=playlist_name,
        public=False,
        description=playlist_description
    )

    sp.playlist_add_items(playlist_id=playlist['id'], items=track_uris)
    playlist_url = playlist['external_urls']['spotify']
    print(f"Successfully created playlist '{playlist_name}'!")
    
    return playlist_url, found_songs